# Sends an MS Teams notification if a PR is marked Stale
# Currently uses MessageCard and not AdaptiveCard.
# Changing to AdaptiveCard might require forking & changing the action

name: Notify Team on stale pull requests

on: 
  pull_request:
    types: [labeled, unlabeled]

jobs:
  notify:
    name: A job to send MS notifications stale prs/issues
    if: ${{ github.event.label.name == 'stale' }}
    runs-on: ubuntu-latest
    steps:  
      - name: Debug GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"      
      - uses: actions/checkout@v2
      - name: Notify dedicated teams channel
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MS_TEAMS_HUB_NOTIFICATIONS_WEBHOOK_URI }}
          raw: >-
            {
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",            
                "themeColor": "0076D7",
                "summary": "Stale Pull Request",
                "sections": [{
                    "activityTitle": "${{ github.event.pull_request.title }}",
                    "activitySubtitle": "${{ github.event.pull_request.head.repo.full_name }} from ${{ github.event.pull_request.user.login }}",
                    "activityImage": "${{ github.event.pull_request.user.avatar_url }}",
                    "facts": [{
                        "name": "Assigned to",
                        "value": "${{ github.event.pull_request.requested_reviewers }}"
                    }, {
                        "name": "Updated",
                        "value": "${{ github.event.pull_request.updated_at }}"
                    }, {
                        "name": "Status",
                        "value": "${{ github.event.pull_request.state }}"
                    }],
                    "markdown": true
                }],
                "potentialAction": [{
                    "@type": "OpenUri",
                    "name": "View the PR",
                    "targets": [{
                        "os": "default",
                        "uri": "${{ github.event.pull_request.html_url }}"
                    }]
                }]
            }
